baseURL = "https://the-going.github.io/evlproject/"
canonifyurls = true
languageCode = "en-US"
title = "Xenomai 4"
theme = "relearn"
copyright = "Copyright 2021 - The Xenomai project."
enableGitInfo = true

[params]
author = "Philippe Gerum <rpm@xenomai.org>"
description = "Xenomai 4 project"
disableSearch = false
disableInlineCopyToClipBoard = true
disableBreadcrumb = false
themeVariant = "evl"
disableShortcutsTitle = true
disableLandingPageButton = true
evlTrackingKernel = "v5.14"
evlLTSBranch = "v5.10.y"
evlLTSLatest = "v5.10.70-evl1"
evlLibLatest = "r27"

[markup]
  [markup.highlight]
  style = "base16-snazzy" # choose a color theme or create your own
  guessSyntax = true     # if set to true, avoid unstyled code if no language was given but mermaid code fences will not work anymore
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true

[[menu.shortcuts]]
name = "<i class='fas fa-home'></i> Home"
identifier = "Home"
#url = "/"
weight = 1

[[menu.shortcuts]]
name = "<i class='fas fa-comments'></i> RIOT channel"
identifier = "RIOT"
url = "https://riot.im/app/#/room/#evlproject:matrix.org/"
weight = 2

[[menu.shortcuts]]
name = "<i class='fas fa-comment-dots'></i> Mailing list"
identifier = "ML"
url = "https://xenomai.org/mailman/listinfo/xenomai/"
weight = 3

[outputs]
home = [ "HTML", "RSS", "JSON"]
