baseURL = "https://evenless.org/"
languageCode = "en-us"
title = "Evenless"
theme = "hugo-theme-learn"

[params]
author = "Philippe Gerum <rpm@xenomai.org>"
description = "Evenless co-kernel"
disableSearch = false
disableInlineCopyToClipBoard = true
themeVariant = "blue"

[outputs]
home = [ "HTML", "RSS", "JSON"]
