baseURL = "https://evlproject.org/"
languageCode = "en-US"
title = "EVL project"
theme = "hugo-theme-learn"
copyright = "Copyright 2020 - The EVL project."
enableGitInfo = true

[params]
author = "Philippe Gerum <rpm@xenomai.org>"
description = "EVL project"
disableSearch = false
disableInlineCopyToClipBoard = true
disableBreadcrumb = false
themeVariant = "evl"
disableShortcutsTitle = true
evlTrackingKernel = "v5.7"
evlLTSBranch = "evl/v5.4"
evlLTSLatest = "v5.4.45-evl2"
evlLibLatest = "r21"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[[menu.shortcuts]]
name = "<i class='fas fa-home'></i> Home"
identifier = "Home"
url = "/"
weight = 1

[[menu.shortcuts]]
name = "<i class='fas fa-comments'></i> RIOT channel"
identifier = "RIOT"
url = "https://riot.im/app/#/room/#evlproject:matrix.org/"
weight = 2

[[menu.shortcuts]]
name = "<i class='fas fa-comment-dots'></i> Mailing list"
identifier = "ML"
url = "https://evlproject.org/mailman/listinfo/evl/"
weight = 3

[outputs]
home = [ "HTML", "RSS", "JSON"]
