baseURL = "https://evlproject.org/"
languageCode = "en-US"
title = "EVL project"
theme = "hugo-theme-learn"
copyright = "Copyright 2019 - The EVL project."

[params]
author = "Philippe Gerum <rpm@xenomai.org>"
description = "EVL project"
disableSearch = false
disableInlineCopyToClipBoard = true
disableBreadcrumb = false
themeVariant = "evl"
disableShortcutsTitle=true

[[menu.shortcuts]]
name = "<i class='fas fa-envelope'></i> Contact"
identifier = "Contact"
url = "mailto:Philippe Gerum <rpm@xenomai.org>"
weight = 20

[outputs]
home = [ "HTML", "RSS", "JSON"]
