baseURL = "https://evlproject.org/"
languageCode = "en-US"
title = "Xenomai 4"
theme = "hugo-theme-learn"
copyright = "Copyright 2021 - The Xenomai project."
enableGitInfo = true

[params]
author = "Philippe Gerum <rpm@xenomai.org>"
description = "Xenomai 4 project"
disableSearch = false
disableInlineCopyToClipBoard = true
disableBreadcrumb = false
themeVariant = "evl"
disableShortcutsTitle = true
disableLandingPageButton = true
evlTrackingKernel = "v5.13"
evlLTSBranch = "v5.10.y"
evlLTSLatest = "v5.10.42-evl1"
evlLibLatest = "r25"

[markup]
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true

[[menu.shortcuts]]
name = "<i class='fas fa-home'></i> Home"
identifier = "Home"
url = "/"
weight = 1

[[menu.shortcuts]]
name = "<i class='fas fa-comments'></i> RIOT channel"
identifier = "RIOT"
url = "https://riot.im/app/#/room/#evlproject:matrix.org/"
weight = 2

[[menu.shortcuts]]
name = "<i class='fas fa-comment-dots'></i> Mailing list"
identifier = "ML"
url = "https://evlproject.org/mailman/listinfo/evl/"
weight = 3

[outputs]
home = [ "HTML", "RSS", "JSON"]
